### PR TITLE
Upgrade ORT ver to 1.11.0

### PR DESCRIPTION
**Pull request by pranavsharma**
Upgrade ORT ver to 1.11.0

### CODE REVIEW

**Review by deadeyegoodwin — COMMENTED** [review]
Looks ok, I will need to run a full CI to verify.

**Comment by deadeyegoodwin** [comment]
@pranavsharma We see a compilation failure on windows. Did you test that build?


    12>C:\workspace\onnxruntime\cmake\external\onnx-tensorrt\onnx_utils.hpp(155,104): error C2660: 'google::protobuf::io::CodedInputStream::SetTotalBytesLimit': function does not take 2 arguments (compiling source file C:\workspace\onnxruntime\cmake\external\onnx-tensorrt\ModelImporter.cpp) [C:\workspace\build\Release\external\onnx-tensorrt\nvonnxparser_static.vcxproj] [C:\tmp\tritonbuild\onnxruntime\build\ort_target.vcxproj]
    12>C:\workspace\onnxruntime\cmake\external\onnx-tensorrt\ModelImporter.cpp(362,108): error C2660: 'google::protobuf::io::CodedInputStream::SetTotalBytesLimit': function does not take 2 arguments [C:\workspace\build\Release\external\onnx-tensorrt\nvonnxparser_static.vcxproj] [C:\tmp\tritonbuild\onnxruntime\build\ort_target.vcxproj]
    12>C:\workspace\onnxruntime\cmake\external\onnx-tensorrt\ModelImporter.cpp(379,108): error C2660: 'google::protobuf::io::CodedInputStream::SetTotalBytesLimit': function does not take 2 arguments [C:\workspace\build\Release\external\onnx-tensorrt\nvonnxparser_static.vcxproj] [C:\tmp\tritonbuild\onnxruntime\build\ort_target.vcxproj]

**Comment by deadeyegoodwin** [comment]
> @pranavsharma We see a compilation failure on windows. Did you test that build?
> 
> ```
> 12>C:\workspace\onnxruntime\cmake\external\onnx-tensorrt\onnx_utils.hpp(155,104): error C2660: 'google::protobuf::io::CodedInputStream::SetTotalBytesLimit': function does not take 2 arguments (compiling source file C:\workspace\onnxruntime\cmake\external\onnx-tensorrt\ModelImporter.cpp) [C:\workspace\build\Release\external\onnx-tensorrt\nvonnxparser_static.vcxproj] [C:\tmp\tritonbuild\onnxruntime\build\ort_target.vcxproj]
> 12>C:\workspace\onnxruntime\cmake\external\onnx-tensorrt\ModelImporter.cpp(362,108): error C2660: 'google::protobuf::io::CodedInputStream::SetTotalBytesLimit': function does not take 2 arguments [C:\workspace\build\Release\external\onnx-tensorrt\nvonnxparser_static.vcxproj] [C:\tmp\tritonbuild\onnxruntime\build\ort_target.vcxproj]
> 12>C:\workspace\onnxruntime\cmake\external\onnx-tensorrt\ModelImporter.cpp(379,108): error C2660: 'google::protobuf::io::CodedInputStream::SetTotalBytesLimit': function does not take 2 arguments [C:\workspace\build\Release\external\onnx-tensorrt\nvonnxparser_static.vcxproj] [C:\tmp\tritonbuild\onnxruntime\build\ort_target.vcxproj]
> ```

Our windows build uses an older version of TensorRT, so perhaps 1.11.0 requires a more recent TensorRT?

**Comment by deadeyegoodwin** [comment]
We also see many of these warnings on Ubuntu build:

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed
/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1873): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

And more problematically we see a couple of errors like the following on Ubuntu:

In file included from /workspace/onnxruntime/cmake/external/onnx-tensorrt/ModelImporter.cpp:8:
/workspace/onnxruntime/cmake/external/onnx-tensorrt/onnx_utils.hpp: In function ‘bool ParseFromFile_WAR(google::protobuf::Message*, const char*)’:
/workspace/onnxruntime/cmake/external/onnx-tensorrt/onnx_utils.hpp:155:104: error: no matching function for call to ‘google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int, int)’
  155 |     coded_input.SetTotalBytesLimit(std::numeric_limits<int>::max(), std::numeric_limits<int>::max() / 4);
      |                                                                                                        ^
In file included from /workspace/build/Release/external/onnx/onnx/onnx-ml.pb.h:23,
                 from /workspace/onnxruntime/onnxruntime/../cmake/external/onnx/onnx/onnx_pb.h:52,
                 from /workspace/onnxruntime/cmake/external/onnx-tensorrt/ShapedWeights.hpp:8,
                 from /workspace/onnxruntime/cmake/external/onnx-tensorrt/onnx2trt.hpp:8,
                 from /workspace/onnxruntime/cmake/external/onnx-tensorrt/ImporterContext.hpp:7,
                 from /workspace/onnxruntime/cmake/external/onnx-tensorrt/ModelImporter.hpp:7,
                 from /workspace/onnxruntime/cmake/external/onnx-tensorrt/ModelImporter.cpp:5:
/workspace/onnxruntime/cmake/external/protobuf/src/google/protobuf/io/coded_stream.h:401:8: note: candidate: ‘void google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int)’
  401 |   void SetTotalBytesLimit(int total_bytes_limit);
      |        ^~~~~~~~~~~~~~~~~~
/workspace/onnxruntime/cmake/external/protobuf/src/google/protobuf/io/coded_stream.h:401:8: note:   candidate expects 1 argument, 2 provided

**Comment by pranavsharma** [comment]
Ok, let me follow up.

**Comment by pranavsharma** [comment]
It looks like onnx-tensorrt parser was upgraded to accommodate the protobuf upgrade in ORT in 1.11. I'm testing the fix right now.

**Comment by pranavsharma** [comment]
@deadeyegoodwin it's longer than expected for me to test due to some issue with my env. I'll try to test tonight, but if you get a chance before that it'll be great. All the errors you've seen so far was because of the tensorrt parser. Thanks!

**Comment by pranavsharma** [comment]
> It looks like you just reverted this change. I will start a CI with only the server repo change.

Yeah, because of this line https://github.com/triton-inference-server/onnxruntime_backend/blob/main/tools/gen_ort_dockerfile.py#L560. No special config is required; it should just use all the ORT defaults for 1.11.

**Comment by CoderHam** [comment]
@pranavsharma can this PR be closed if it is no longer needed

**Comment by pranavsharma** [comment]
I tested this just now with ORT 1.11 and it works just fine. No PR needed.

**Pull request closed without merging**
